# -*- coding: utf-8 -*-
"""praktikum 6 G.211.25.0078.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8o3XZaIf-GflDSEta-vvNok-H79hoOj
"""

# Fibonacci
def fib(n):
    if n <= 1:
        return n
    return fib(n-1) + fib(n-2)

print("=== DERET FIBONACCI ===")
print(f"Nilai Fibonacci pada posisi 6 adalah {fib(6)}")


# Subset
def cari_subset(data, current=[]):
    if len(data) == 0:
        print("Subset:", current)
        return

    cari_subset(data[1:], current)
    cari_subset(data[1:], current + [data[0]])

print("\n=== DAFTAR SUBSET ===")
cari_subset([1, 2, 3])


# Binary String
def biner(panjang, hasil=""):
    if panjang == 0:
        print("Biner:", hasil)
        return

    biner(panjang - 1, hasil + "0")
    biner(panjang - 1, hasil + "1")

print("\n=== STRING BINER PANJANG 3 ===")
biner(3)