# -*- coding: utf-8 -*-
"""praktikum 5 (G.211.25.0078).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiHtGHUUognlQYJkuXkTrL9FMWw0npk7

1. bubble sort
Mulai
Input data
Ulangi dari i = 0 sampai n-1
    Ulangi dari j = 0 sampai n-i-1
        Jika data[j] > data[j+1]
            Tukar data
Tampilkan hasil
Selesai
"""

def bubble_sort(data):
    n = len(data)

    for i in range(n):
        for j in range(0, n-i-1):
            if data[j] > data[j+1]:
                data[j], data[j+1] = data[j+1], data[j]

data = [64, 34, 25, 12, 22]
bubble_sort(data)

print("Hasil:", data)

"""Kompleksitas
Best Case → O(n)
Average Case → O(n²)
Worst Case → O(n²)

2.Selection sort
Mulai
Input data
Cari elemen terkecil
Tukar dengan posisi awal
Ulangi sampai semua data urut
Selesai
"""

def selection_sort(data):
    for i in range(len(data)):
        min_idx = i

        for j in range(i+1, len(data)):
            if data[j] < data[min_idx]:
                min_idx = j

        data[i], data[min_idx] = data[min_idx], data[i]

data = [64, 25, 12, 22, 11]
selection_sort(data)

print("Hasil:", data)

"""Kompleksitas
Best → O(n²)
Average → O(n²)
Worst → O(n²)

3.insertion sort
  Mulai
Ambil elemen kedua
Bandingkan dengan sebelumnya
Geser jika lebih besar
Ulangi sampai selesai
Selesai
"""

def insertion_sort(data):

    for i in range(1, len(data)):
        key = data[i]
        j = i - 1

        while j >= 0 and key < data[j]:
            data[j + 1] = data[j]
            j -= 1

        data[j + 1] = key

data = [12, 11, 13, 5, 6]

insertion_sort(data)

print("Hasil:", data)

"""Kompleksitas
Best → O(n)
Average → O(n²)
Worst → O(n²)

4.merge sort
Mulai
Bagi data menjadi dua
Urutkan masing-masing bagian
Gabungkan kembali
Selesai
"""

def merge_sort(data):

    if len(data) > 1:

        mid = len(data)//2
        kiri = data[:mid]
        kanan = data[mid:]

        merge_sort(kiri)
        merge_sort(kanan)

        i = j = k = 0

        while i < len(kiri) and j < len(kanan):

            if kiri[i] < kanan[j]:
                data[k] = kiri[i]
                i += 1
            else:
                data[k] = kanan[j]
                j += 1

            k += 1

        while i < len(kiri):
            data[k] = kiri[i]
            i += 1
            k += 1

        while j < len(kanan):
            data[k] = kanan[j]
            j += 1
            k += 1

data = [38, 27, 43, 3, 9]
merge_sort(data)

print("Hasil:", data)

"""Kompleksitas
Best → O(n log n)
Average → O(n log n)
Worst → O(n log n)
"""