# -*- coding: utf-8 -*-
"""praktikum 7 G.211.25.0078.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8o3XZaIf-GflDSEta-vvNok-H79hoOj
"""

# Menghitung rata-rata
def avg(data):
    jumlah = 0
    for x in data:
        jumlah += x
    return jumlah / len(data)

# Mengubah baris menjadi kolom
def ubah_kolom(data):
    hasil = []
    for i in range(len(data[0])):
        kolom = []
        for j in range(len(data)):
            kolom.append(data[j][i])
        hasil.append(kolom)
    return hasil

# Centering data
def center(data):
    kolom = ubah_kolom(data)
    rata2 = []

    for k in kolom:
        rata2.append(avg(k))

    data_baru = []
    for baris in data:
        temp = []
        for i in range(len(baris)):
            temp.append(baris[i] - rata2[i])
        data_baru.append(temp)

    return data_baru

# Matriks kovarians
def cov_matrix(data):
    n = len(data)
    m = len(data[0])

    hasil = []

    for i in range(m):
        baris = []

        for j in range(m):
            total = 0

            for k in range(n):
                total += data[k][i] * data[k][j]

            baris.append(total / (n - 1))

        hasil.append(baris)

    return hasil

# Mencari eigenvector dominan
def power_iterasi(mat):
    v = [1.0] * len(mat)

    for _ in range(50):
        baru = []

        for i in range(len(mat)):
            nilai = 0
            for j in range(len(mat)):
                nilai += mat[i][j] * v[j]
            baru.append(nilai)

        akar = 0
        for x in baru:
            akar += x * x

        akar = akar ** 0.5

        v = [x / akar for x in baru]

    return v

# Proyeksi PCA
def pca(data):
    data = center(data)

    cov = cov_matrix(data)

    pc1 = power_iterasi(cov)

    hasil = []

    for baris in data:
        nilai = 0
        for i in range(len(pc1)):
            nilai += baris[i] * pc1[i]

        hasil.append([round(nilai, 3)])

    return hasil


# =====================
# DATA
# =====================

X = [
    [2, 3],
    [3, 5],
    [4, 2],
    [5, 4]
]

print("Hasil PCA:")

for row in pca(X):
    print(row)