# -*- coding: utf-8 -*-
"""praktikum 8 G.211.25.0078.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8o3XZaIf-GflDSEta-vvNok-H79hoOj
"""

# Fibonacci Rekursif
# Time  : O(2^n)
# Space : O(n)

def fibonacci_biasa(x):
    if x < 2:
        return x
    return fibonacci_biasa(x - 1) + fibonacci_biasa(x - 2)

print("Fibonacci Rekursif =", fibonacci_biasa(10))

# Fibonacci Memoization
# Time  : O(n)
# Space : O(n)

cache = {}

def fibonacci_cache(x):
    if x <= 1:
        return x

    if x not in cache:
        cache[x] = fibonacci_cache(x - 1) + fibonacci_cache(x - 2)

    return cache[x]

print("Fibonacci Memo =", fibonacci_cache(50))

# Fibonacci Dynamic Programming
# Time  : O(n)
# Space : O(n)

def fibonacci_tabel(x):
    if x <= 1:
        return x

    nilai = [0, 1]

    for i in range(2, x + 1):
        nilai.append(nilai[i - 1] + nilai[i - 2])

    return nilai[x]

print("Fibonacci DP =", fibonacci_tabel(50))

# Fibonacci Optimasi Ruang
# Time  : O(n)
# Space : O(1)

def fibonacci_cepat(x):
    if x <= 1:
        return x

    pertama, kedua = 0, 1

    for _ in range(x - 1):
        pertama, kedua = kedua, pertama + kedua

    return kedua

print("Fibonacci Optimasi =", fibonacci_cepat(50))

# Coin Change Greedy
# Time  : O(n + k)
# Space : O(k)

def tukar_uang(koin, target):
    koin = sorted(koin, reverse=True)

    daftar = []

    for nilai in koin:
        while target >= nilai:
            daftar.append(nilai)
            target -= nilai

    return daftar

pecahan = [100, 50, 25, 10, 5, 1]
uang = 289

jawaban = tukar_uang(pecahan, uang)

print("Koin Terpilih =", jawaban)
print("Total Koin =", len(jawaban))


# Coin Change DP
# Time  : O(n × A)
# Space : O(A)

def kombinasi_koin(koin, target):
    cara = [0] * (target + 1)
    cara[0] = 1

    for nilai in koin:
        for i in range(nilai, target + 1):
            cara[i] = cara[i] + cara[i - nilai]

    return cara[target]

print("Jumlah Cara =", kombinasi_koin([1, 2, 5], 5))