# -*- coding: utf-8 -*-
"""praktikum 3 (G.211.25.0078).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiHtGHUUognlQYJkuXkTrL9FMWw0npk7
"""

Mulai

Input jumlah node
Input matriks graf

Set jarak awal = tak hingga
Set node awal = 0
Jarak node awal = 0

Selama masih ada node yang belum dikunjungi:
    Pilih node dengan jarak terkecil
    Tandai node sudah dikunjungi

    Untuk setiap tetangga:
        Hitung jarak baru
        Jika jarak baru lebih kecil:
            Update jarak

Tampilkan hasil jarak terpendek

Selesai

import heapq

def dijkstra(graph, start):
    jarak = {node: float('inf') for node in graph}
    jarak[start] = 0

    antrian = [(0, start)]

    while antrian:
        jarak_sekarang, node = heapq.heappop(antrian)

        for tetangga, bobot in graph[node]:
            total = jarak_sekarang + bobot

            if total < jarak[tetangga]:
                jarak[tetangga] = total
                heapq.heappush(antrian, (total, tetangga))

    return jarak


graf = {
    'A': [('B', 4), ('C', 2)],
    'B': [('D', 5)],
    'C': [('B', 1), ('D', 8)],
    'D': []
}

awal = 'A'

hasil = dijkstra(graf, awal)

print("Jarak terpendek dari", awal)
for node, nilai in hasil.items():
    print(f"{node} = {nilai}")