# -*- coding: utf-8 -*-
"""TUGAS 1 KOMPLEKSITAS_G.211.25.0078.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwSsyJgBtQV9H0KOxoyzVRgMcdfYyQ5M
"""

def faktorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * faktorial(n-1)

# contoh
print(faktorial(10))
print(faktorial(7))

import sys
sys.set_int_max_str_digits(0) # Set to 0 for unlimited digits, or a sufficiently large number

def factorial_while(n):
    if n < 0:
        return None
    result = 1
    while n > 1:
        result *= n
        n -= 1
    return result

print(f"10177! = {factorial_while(10177)}")
print(f"5! = {factorial_while(5)}")
print(f"0! = {factorial_while(0)}")

def factorial_tail(n, acc=1):
    if n < 0:
        return None
    if n == 0 or n == 1:
        return acc
    return factorial_tail(n - 1, acc * n)

# Test
print(f"5! = {factorial_tail(5)}")

from decimal import Decimal, getcontext

def factorial_binary(n):
    getcontext().prec = 10000

    if n < 0:
        return None
    if n == 0 or n == 1:
        return Decimal(1)

    def product(a, b):
        if a > b:
            return Decimal(1)
        if a == b:
            return Decimal(a)
        if b - a == 1:
            return Decimal(a) * Decimal(b)
        mid = (a + b) // 2
        return product(a, mid) * product(mid + 1, b)

    return product(1, n)

# Test
print(f"10! = {factorial_binary(10)}")

def factorial_recursive(n):
    if not isinstance(n, int):
        raise ValueError("Input harus bilangan bulat")
    if n < 0:
        raise ValueError("Factorial tidak didefinisikan untuk bilangan negatif")

    if n == 0 or n == 1:
        return 1
    return n * factorial_recursive(n - 1)

# Test
for n in [5, 10, 15, 20]:
    print(f"{n}! = {factorial_recursive(n)}")